---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: welcome-app
  name: welcome-app-deployment
  labels:
    app: welcome-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: welcome-app-deployment=bonyscott/welcome-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-app
          image: bonyscott/welcome-app:v2
          ports:
            - containerPort: 8080
