apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app-deployment
  namespace: welcome-app
  labels:
    app: welcome-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      serviceAccountName: welcome-app-service-account
      containers:
        - name: welcome-app
          image: bonyscott/welcome-app:0d7397d
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
          - secretRef:
              name: welcome-app-secret