resources:
  # - deployment.yaml
  # - service.yaml
  # - ingress.yaml
  - canaryingress.yaml
  - stable-ingress.yaml
  - service-account.yaml
  - secret-store.yaml
  - external-secrets.yaml
  - canary-service.yaml
  - stable-service.yaml
  - rollout.yaml