---
apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  namespace: welcome-app
spec:
  selector:
    app: welcome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
